export const metadata = {
  title: 'Terms of Service — RoastMePal',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background px-4 py-20">
      <div className="max-w-2xl mx-auto">
        <p className="eyebrow mb-3">Legal</p>
        <h1 className="font-display text-4xl font-light text-white mb-8">Terms of Service</h1>

        <div className="card-surface space-y-6 text-sm text-muted-foreground leading-relaxed">
          <div>
            <h2 className="text-white font-medium mb-2">Use of the service</h2>
            <p>
              RoastMePal is a tool for entertainment and feedback purposes. By using this service,
              you agree not to submit content that is illegal, defamatory, or violates the rights of
              others. The AI-generated roasts are satirical in nature and should not be taken as
              professional business advice.
            </p>
          </div>

          <div>
            <h2 className="text-white font-medium mb-2">Your content</h2>
            <p>
              You retain ownership of the startup ideas you submit. By submitting them, you grant
              RoastMePal a non-exclusive license to store and display the content within the app.
              We may use anonymized submissions to improve the service.
            </p>
          </div>

          <div>
            <h2 className="text-white font-medium mb-2">Disclaimer</h2>
            <p>
              The roasts generated by RoastMePal are produced by AI and are intended for entertainment.
              We make no guarantees about the accuracy, quality, or appropriateness of the generated
              content. Use at your own risk — and don&apos;t take it personally.
            </p>
          </div>

          <div>
            <h2 className="text-white font-medium mb-2">Changes</h2>
            <p>
              We may update these terms from time to time. Continued use of the service after changes
              constitutes acceptance of the new terms.
            </p>
          </div>

          <p className="text-xs text-muted-foreground/50">Last updated: April 2026</p>
        </div>
      </div>
    </main>
  )
}
